// Code generated by ai-platform-generator. DO NOT EDIT.
// Regenerate via: ai-platform-generator generate ...

// Package v1alpha1 contains API Schema definitions for the
// observability.cnoe.io v1alpha1 API group.
// +kubebuilder:object:generate=true
// +groupName=observability.cnoe.io
package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"sigs.k8s.io/controller-runtime/pkg/scheme"
)

// GroupVersion is the API GroupVersion used to register these objects.
var GroupVersion = metav1.GroupVersion{Group: "observability.cnoe.io", Version: "v1alpha1"}

// SchemeBuilder is used to add go types to the GroupVersionKind scheme.
var SchemeBuilder = &scheme.Builder{GroupVersion: schemaGV()}

// AddToScheme registers this API group's types with a scheme.
var AddToScheme = SchemeBuilder.AddToScheme

func schemaGV() runtime.GroupVersioner {
	return runtime.GroupVersioner(metav1.GroupVersion{
		Group:   "observability.cnoe.io",
		Version: "v1alpha1",
	})
}

// MonitoringServiceSpec defines the desired state of MonitoringService.
type MonitoringServiceSpec struct {
	// Whether alert routing is enabled for this monitor.
	// +kubebuilder:validation:Required
	AlertEnabled bool `json:"alertEnabled"`
	// Scrape interval, e.g. '30s' or '1m'.
	// +kubebuilder:validation:Required
	Interval string `json:"interval"`
	// List of target hostnames or service URIs to monitor.
	// +kubebuilder:validation:Required
	Targets []string `json:"targets"`
}

// MonitoringServiceStatus defines the observed state of MonitoringService.
type MonitoringServiceStatus struct {
	// ObservedGeneration is the most recent .metadata.generation reconciled
	// by the controller.
	ObservedGeneration int64 `json:"observedGeneration,omitempty"`

	// Conditions represent the latest available observations of the
	// resource's state.
	// +patchMergeKey=type
	// +patchStrategy=merge
	Conditions []metav1.Condition `json:"conditions,omitempty" patchMergeKey:"type" patchStrategy:"merge"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status

// MonitoringService is the Schema for the monitoringservices API.
type MonitoringService struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   MonitoringServiceSpec   `json:"spec,omitempty"`
	Status MonitoringServiceStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// MonitoringServiceList contains a list of MonitoringService.
type MonitoringServiceList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []MonitoringService `json:"items"`
}

func init() {
	SchemeBuilder.Register(&MonitoringService{}, &MonitoringServiceList{})
}
