"""Golden-file matrix for the canonical scenarios x every registered generator.

The matrix is the eight curated scenarios from
``docs/ddd/08-implementation-roadmap.md`` §10 (also baked into
:class:`DemoCatalog`) cross-multiplied with every concrete
:class:`ArtifactGenerator` registered in
:mod:`...domain.generation.generators` — currently OpenAPI, CRD,
instance, kustomization, mcp_server and go_controller.

For each cell of the matrix this module:

1. Builds a :class:`CodegenRequest` from the catalogue entry.
2. Constructs the IR via :meth:`OpenAPIDocument.from_request`.
3. Runs the generator end-to-end through :class:`IdempotencyVerifier`
   (3 runs) so byte-stability is asserted in addition to content
   equality — a non-deterministic generator fails *here* rather than
   silently corrupting golden expectations.
4. Compares the actual rendered bytes against checked-in fixtures
   under ``tests/golden/expected/<scenario>/<generator>/...``.

The fixture files are stored on disk so reviewers can inspect a diff
when intentionally evolving a generator. To intentionally update them,
run::

    pytest tests/golden -k canonical --update-golden

When ``--update-golden`` is passed the test overwrites the expectation
files with the freshly generated bytes and marks itself :func:`xfail`
so the run is recognisable as a fixture regeneration rather than a
normal pass.

Generator availability: a generator that is not currently importable
(e.g. one of L's or M's modules absent during Wave-4 reconciliation)
shows up in :func:`unavailable_generators` and the corresponding cells
are skipped with a clear message rather than failing.
"""

from __future__ import annotations

import tempfile
from pathlib import Path

import pytest

from ai_platform_generator.adapters.llm.demo_catalog import DemoCatalog, DemoScenario
from ai_platform_generator.domain.aggregates import (
    CodegenRequest,
    OpenAPIDocument,
    RenderedArtifact,
)
from ai_platform_generator.domain.generation.artifact_generator import ArtifactGenerator
from ai_platform_generator.domain.generation.generators import (
    default_generators,
    unavailable_generators,
)
from ai_platform_generator.domain.generation.idempotency_verifier import (
    IdempotencyVerifier,
)

#: Directory holding the checked-in golden expectation files.
EXPECTED_ROOT = Path(__file__).resolve().parent.parent / "expected"

#: The eight canonical scenarios, in catalogue order.
_CATALOGUE = DemoCatalog()

# Snapshot the generator instances once so parametrize ids are stable.
_GENERATOR_INSTANCES: tuple[ArtifactGenerator, ...] = default_generators()


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _scenario_dir(scenario_name: str, generator_name: str) -> Path:
    """Return ``tests/golden/expected/<scenario>/<generator>``."""
    return EXPECTED_ROOT / scenario_name / generator_name


def _build_ir(scenario: DemoScenario) -> OpenAPIDocument:
    """Round-trip the scenario's request dict to a canonical IR."""
    request = CodegenRequest.from_dict(scenario.request)
    return OpenAPIDocument.from_request(request)


def _generate_into_tmp(
    generator: ArtifactGenerator, ir: OpenAPIDocument
) -> dict[str, bytes]:
    """Run ``generator`` once and return ``{relative POSIX path: payload}``."""
    with tempfile.TemporaryDirectory(prefix="golden-") as td:
        target = Path(td)
        artefacts: tuple[RenderedArtifact, ...] = generator.generate(ir, target)
        return {art.path.as_posix(): art.payload for art in artefacts}


def _read_expected(expected_dir: Path) -> dict[str, bytes]:
    """Read every file under ``expected_dir`` keyed by relative POSIX path."""
    if not expected_dir.exists():
        return {}
    out: dict[str, bytes] = {}
    for path in sorted(expected_dir.rglob("*")):
        if not path.is_file():
            continue
        rel = path.relative_to(expected_dir).as_posix()
        out[rel] = path.read_bytes()
    return out


def _write_expected(expected_dir: Path, actual: dict[str, bytes]) -> None:
    """Rewrite the expected tree from scratch.

    Removing the old tree first ensures stale files (e.g. from a
    generator that used to emit ``foo.txt`` but no longer does) are
    purged on update.
    """
    if expected_dir.exists():
        # Walk in reverse so files are unlinked before their dirs.
        for path in sorted(expected_dir.rglob("*"), reverse=True):
            if path.is_file():
                path.unlink()
            elif path.is_dir():
                try:
                    path.rmdir()
                except OSError:
                    pass
    expected_dir.mkdir(parents=True, exist_ok=True)
    for rel, payload in actual.items():
        out = expected_dir / rel
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_bytes(payload)


# ---------------------------------------------------------------------------
# Matrix test
# ---------------------------------------------------------------------------


@pytest.mark.golden
@pytest.mark.parametrize(
    "scenario", _CATALOGUE.scenarios, ids=[s.name for s in _CATALOGUE.scenarios]
)
@pytest.mark.parametrize(
    "generator", _GENERATOR_INSTANCES, ids=[g.name for g in _GENERATOR_INSTANCES]
)
def test_canonical_scenario_matches_golden(
    scenario: DemoScenario,
    generator: ArtifactGenerator,
    update_golden: bool,
) -> None:
    """Compare generator output for a scenario against the on-disk fixture.

    With ``--update-golden`` the fixture is rewritten and the test is
    marked :func:`xfail` so the user notices the rewrite. Without the
    flag the comparison is byte-exact and any drift fails loudly.
    """
    missing = unavailable_generators()
    if generator.name in missing:
        pytest.skip(
            f"generator {generator.name!r} is not yet available "
            f"({missing[generator.name]}); Wave-4 reconciliation will re-enable"
        )

    ir = _build_ir(scenario)

    # Determinism guard — fail loudly here, not in the comparison phase.
    IdempotencyVerifier().verify_byte_stable(generator, ir, runs=3)

    actual = _generate_into_tmp(generator, ir)
    expected_dir = _scenario_dir(scenario.name, generator.name)

    if update_golden:
        _write_expected(expected_dir, actual)
        pytest.xfail(
            f"golden updated for {scenario.name}/{generator.name} — "
            f"{len(actual)} files written under "
            f"tests/golden/expected/{scenario.name}/{generator.name}"
        )

    expected = _read_expected(expected_dir)
    if not expected:
        pytest.fail(
            f"no golden fixture at {expected_dir} — run with "
            "--update-golden to create it"
        )

    missing_files = sorted(set(actual) - set(expected))
    extra_files = sorted(set(expected) - set(actual))
    assert not missing_files, (
        f"{scenario.name}/{generator.name}: actual output has files with "
        f"no golden expectation: {missing_files!r}. Re-run with --update-golden."
    )
    assert not extra_files, (
        f"{scenario.name}/{generator.name}: golden directory has files no "
        f"generator produced: {extra_files!r}. Delete them or re-run with "
        "--update-golden."
    )

    for relpath in sorted(actual):
        assert actual[relpath] == expected[relpath], (
            f"{scenario.name}/{generator.name}: byte-mismatch for "
            f"{relpath!r}. Inspect "
            f"tests/golden/expected/{scenario.name}/{generator.name}/{relpath} "
            "or re-run with --update-golden if the change was intentional."
        )
