// Code generated by ai-platform-generator. DO NOT EDIT.
// Regenerate via: ai-platform-generator generate ...

// Package v1alpha1 contains API Schema definitions for the
// datascience.cnoe.io v1alpha1 API group.
// +kubebuilder:object:generate=true
// +groupName=datascience.cnoe.io
package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"sigs.k8s.io/controller-runtime/pkg/scheme"
)

// GroupVersion is the API GroupVersion used to register these objects.
var GroupVersion = metav1.GroupVersion{Group: "datascience.cnoe.io", Version: "v1alpha1"}

// SchemeBuilder is used to add go types to the GroupVersionKind scheme.
var SchemeBuilder = &scheme.Builder{GroupVersion: schemaGV()}

// AddToScheme registers this API group's types with a scheme.
var AddToScheme = SchemeBuilder.AddToScheme

func schemaGV() runtime.GroupVersioner {
	return runtime.GroupVersioner(metav1.GroupVersion{
		Group:   "datascience.cnoe.io",
		Version: "v1alpha1",
	})
}

// NotebookSpec defines the desired state of Notebook.
type NotebookSpec struct {
	// CPU request, e.g. '500m' or '2'.
	// +kubebuilder:validation:Required
	Cpu string `json:"cpu"`
	// Whether to attach a GPU to the notebook pod.
	// +kubebuilder:validation:Required
	Gpu bool `json:"gpu"`
	// Memory request, e.g. '4Gi'.
	// +kubebuilder:validation:Required
	Memory string `json:"memory"`
}

// NotebookStatus defines the observed state of Notebook.
type NotebookStatus struct {
	// ObservedGeneration is the most recent .metadata.generation reconciled
	// by the controller.
	ObservedGeneration int64 `json:"observedGeneration,omitempty"`

	// Conditions represent the latest available observations of the
	// resource's state.
	// +patchMergeKey=type
	// +patchStrategy=merge
	Conditions []metav1.Condition `json:"conditions,omitempty" patchMergeKey:"type" patchStrategy:"merge"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status

// Notebook is the Schema for the notebooks API.
type Notebook struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   NotebookSpec   `json:"spec,omitempty"`
	Status NotebookStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// NotebookList contains a list of Notebook.
type NotebookList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Notebook `json:"items"`
}

func init() {
	SchemeBuilder.Register(&Notebook{}, &NotebookList{})
}
