// Code generated by ai-platform-generator. DO NOT EDIT.
// Regenerate via: ai-platform-generator generate ...

package controller

import (
	"context"

	apierrors "k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/log"
	"sigs.k8s.io/controller-runtime/pkg/meta"

	v1alpha1 "github.com/example/cachecluster-operator/api/v1alpha1"
)

// CacheClusterReconciler reconciles a CacheCluster object.
type CacheClusterReconciler struct {
	client.Client
	Scheme *runtime.Scheme
}

// +kubebuilder:rbac:groups=platform.cnoe.io,resources=cacheclusters,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=platform.cnoe.io,resources=cacheclusters/status,verbs=get;update;patch
// +kubebuilder:rbac:groups=platform.cnoe.io,resources=cacheclusters/finalizers,verbs=update

// Reconcile drives the CacheCluster resource toward its desired state.
//
// The skeleton fetches the resource, sets a `Ready=True` condition, and
// returns. Replace the body with real reconciliation logic.
func (r *CacheClusterReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
	logger := log.FromContext(ctx)

	var obj v1alpha1.CacheCluster
	if err := r.Get(ctx, req.NamespacedName, &obj); err != nil {
		if apierrors.IsNotFound(err) {
			// Object was deleted before we could reconcile it; nothing to do.
			return ctrl.Result{}, nil
		}
		logger.Error(err, "unable to fetch CacheCluster")
		return ctrl.Result{}, err
	}

	// TODO: business logic here — translate obj.Spec into the side effects
	// required to bring the cluster into the desired state.

	// Mark the resource Ready=True/Reconciled.
	meta.SetStatusCondition(&obj.Status.Conditions, metav1.Condition{
		Type:               "Ready",
		Status:             metav1.ConditionTrue,
		Reason:             "Reconciled",
		Message:            "CacheCluster reconciled successfully",
		ObservedGeneration: obj.Generation,
	})
	obj.Status.ObservedGeneration = obj.Generation

	// TODO: persist status updates via r.Status().Update(ctx, &obj).
	_ = obj

	return ctrl.Result{}, nil
}

// SetupWithManager wires the reconciler into the controller manager.
func (r *CacheClusterReconciler) SetupWithManager(mgr ctrl.Manager) error {
	return ctrl.NewControllerManagedBy(mgr).
		For(&v1alpha1.CacheCluster{}).
		Complete(r)
}
