apiVersion: platform.cnoe.io/v1alpha1
kind: CustomResource
metadata:
  name: my-customresource-instance
  namespace: default
spec:
  name: example-value
  enabled: true
  config:
    setting1: value1
    setting2: value2
    config: example-value
