apiVersion: monitoring.cnoe.io/v1alpha1
kind: MonitoringService
metadata:
  name: my-monitoringservice-instance
  namespace: default
spec:
  interval: example-value
  retention: example-value
  endpoints:
  - item1
  - item2
  - item3
