#!/usr/bin/env python3
"""
Impressive AI-Powered Kubernetes Extension Generator Demo
This demo showcases the full power of AI-driven API generation with real Kubernetes outputs.
"""

import os
import json
import time
from pathlib import Path
from typing import Dict, Any

# Add the src directory to the path
import sys
sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from ai_platform_generator.agent import PlatformExtensionAgent, CodegenRequest
from ai_platform_generator.codegen import CodeGenerator
from rich.console import Console
from rich.panel import Panel
from rich.table import Table
from rich.syntax import Syntax
from rich.progress import Progress, SpinnerColumn, TextColumn
from rich.layout import Layout
from rich.align import Align
from rich import print as rprint

console = Console()

def print_banner():
    """Print impressive banner"""
    banner = """
[bold cyan]
╔══════════════════════════════════════════════════════════════╗
║                🚀 AI KUBERNETES API GENERATOR 🚀               ║
║                                                              ║
║  Transform natural language into production Kubernetes      ║
║  Custom Resources, APIs, and Controllers in seconds!        ║
╚══════════════════════════════════════════════════════════════╝
[/bold cyan]
"""
    rprint(banner)

def display_processing_animation():
    """Show AI processing animation"""
    with Progress(
        SpinnerColumn(),
        TextColumn("[progress.description]{task.description}"),
        console=console,
        transient=True,
    ) as progress:
        task = progress.add_task("[cyan]🤖 AI analyzing your request...", total=None)
        time.sleep(1)

        progress.update(task, description="[cyan]🧠 Understanding Kubernetes requirements...")
        time.sleep(1)

        progress.update(task, description="[cyan]⚡ Generating OpenAPI specification...")
        time.sleep(1)

        progress.update(task, description="[cyan]🏗️  Creating Kubernetes CRD definitions...")
        time.sleep(1)

        progress.update(task, description="[cyan]📝 Building Controller templates...")
        time.sleep(1)

def display_kubernetes_output(api_result: Dict[str, Any], request: CodegenRequest, yaml_content: str = None):
    """Display impressive Kubernetes outputs"""

    # Create impressive output layout
    layout = Layout()
    layout.split_column(
        Layout(name="header", size=5),
        Layout(name="main"),
        Layout(name="footer", size=3)
    )

    # Header
    header_content = f"[bold green]✅ Successfully Generated: {request.kind} Kubernetes API[/bold green]"
    layout["header"].update(Align.center(Panel(header_content, style="green")))

    # Main content with tabs
    layout["main"].split_row(
        Layout(name="info", size=40),
        Layout(name="code")
    )

    # Info panel
    info_table = Table(title=f"📋 {request.kind} API Details", show_header=False)
    info_table.add_column("Property", style="cyan")
    info_table.add_column("Value", style="white")

    info_table.add_row("🏷️  API Group", request.group)
    info_table.add_row("🔢 Version", request.version)
    info_table.add_row("🎯 Kind", request.kind)
    info_table.add_row("📊 Spec Fields", str(len(request.spec_properties)))

    for field_name, field_info in request.spec_properties.items():
        field_type = field_info.get("type", "string") if isinstance(field_info, dict) else field_info
        info_table.add_row(f"  • {field_name}", f"[yellow]{field_type}[/yellow]")

    layout["info"].update(Panel(info_table, border_style="blue"))

    # Code panel with Kubernetes YAML
    if yaml_content:
        k8s_yaml = yaml_content
    else:
        _, _, k8s_yaml = generate_impressive_k8s_yaml(request)
    syntax = Syntax(k8s_yaml, "yaml", theme="monokai", line_numbers=True)
    layout["code"].update(Panel(syntax, title=f"📄 Generated Kubernetes YAML", border_style="green"))

    layout["footer"].update(Align.center("[dim]💡 Generated by AI - Ready for production deployment[/dim]"))

    console.print(layout)

def generate_impressive_k8s_yaml(request: CodegenRequest) -> tuple[str, str, str]:
    """Generate impressive Kubernetes YAML with multiple resources
    Returns: (crd_yaml, instance_yaml, combined_yaml)
    """

    # Generate CRD
    crd_yaml = f"""apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: {request.kind.lower()}s.{request.group.split('.')[-2]}.{request.group.split('.')[-1]}
  annotations:
    cert-manager.io/inject-ca-from: '{request.group.split(".")[-2]}-{request.group.split(".")[-1]}/{request.kind.lower()}-serving-cert'
spec:
  group: {request.group.split('.')[-2]}.{request.group.split('.')[-1]}
  versions:
  - name: {request.version}
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          apiVersion:
            type: string
            description: f"{request.group}/{request.version}"
          kind:
            type: string
            description: "{request.kind}"
          metadata:
            type: object
          spec:
            type: object
            properties:"""

    for field_name, field_info in request.spec_properties.items():
        field_type = field_info.get("type", "string") if isinstance(field_info, dict) else field_info
        field_desc = field_info.get("description", field_name) if isinstance(field_info, dict) else field_name
        crd_yaml += f"""
              {field_name}:
                type: {field_type}
                description: "{field_desc}" """

    crd_yaml += """
    status:
      type: object
  names:
    kind: """ + request.kind + """
    plural: """ + request.kind.lower() + """s
    singular: """ + request.kind.lower() + """
  scope: Namespaced"""

    # Generate Sample Instance
    sample_spec = {}
    for field_name, field_info in request.spec_properties.items():
        field_type = field_info.get("type", "string") if isinstance(field_info, dict) else field_info

        if field_type == "string":
            sample_spec[field_name] = "example-value"
        elif field_type == "integer":
            sample_spec[field_name] = 3
        elif field_type == "boolean":
            sample_spec[field_name] = True
        else:
            sample_spec[field_name] = "example-value"

    instance_yaml = f"""apiVersion: {request.group.split('.')[-2]}.{request.group.split('.')[-1]}/{request.version}
kind: {request.kind}
metadata:
  name: my-{request.kind.lower()}-instance
  namespace: default
spec:
"""
    for field_name, value in sample_spec.items():
        instance_yaml += f"  {field_name}: {value}\n"

    combined_yaml = crd_yaml + "\n---\n" + instance_yaml

    return crd_yaml, instance_yaml, combined_yaml

def interactive_demo():
    """Run impressive interactive demo"""
    print_banner()

    # Check API configuration
    api_key = os.getenv("OPENROUTER_API_KEY")
    model = os.getenv("OPENROUTER_MODEL", "deepseek/deepseek-chat-v3.1:free")

    if not api_key:
        console.print("[red]❌ OPENROUTER_API_KEY not set![/red]")
        console.print("[yellow]Please set your OpenRouter API key:[/yellow]")
        console.print("export OPENROUTER_API_KEY=\"your-key-here\"")
        return

    console.print(f"[green]✅ OpenRouter API configured[/green]")
    console.print(f"[blue]🧠 Using model: {model}[/blue]")
    console.print()

    # Example requests to show off
    examples = [
        "Create a Kubernetes API for managing Redis clusters with memory, CPU, and persistence settings",
        "I need a Database service API with connection strings, backup schedules, and auto-scaling",
        "Build a Monitoring service API for collecting metrics with intervals and retention policies",
        "Create a Cache service API with eviction policies, memory limits, and cluster configuration"
    ]

    console.print("[bold cyan]🎯 Choose an example or create your own:[/bold cyan]")
    for i, example in enumerate(examples, 1):
        console.print(f"[cyan]{i}.[/cyan] {example}")
    console.print("[cyan]5.[/cyan] [yellow]Custom request...[/yellow]")

    try:
        choice = input("\nEnter choice (1-5): ").strip()

        if choice == "5":
            user_request = input("\n📝 Describe your Kubernetes API: ").strip()
        elif choice in ["1", "2", "3", "4"]:
            user_request = examples[int(choice) - 1]
        else:
            console.print("[red]Invalid choice![/red]")
            return

        if not user_request:
            return

        console.print(f"\n[bold]🚀 Processing: {user_request}[/bold]")

        # Show processing animation
        display_processing_animation()

        # Process with AI
        agent = PlatformExtensionAgent(api_key=api_key, model=model)

        try:
            console.print("[cyan]🤖 AI is generating your Kubernetes API...[/cyan]")
            parsed_request = agent.parse_request(user_request)

            # Generate and save all results
            output_dir = Path("generated_specs")
            output_dir.mkdir(exist_ok=True)

            # Generate OpenAPI spec
            codegen = CodeGenerator()
            openapi_spec = codegen.generate_openapi_spec(parsed_request)

            # Generate Kubernetes YAML files
            crd_yaml, instance_yaml, combined_yaml = generate_impressive_k8s_yaml(parsed_request)

            # Save OpenAPI specification
            openapi_filename = f"{parsed_request.kind.lower()}_demo.json"
            openapi_filepath = output_dir / openapi_filename

            with open(openapi_filepath, 'w') as f:
                json.dump(openapi_spec, f, indent=2)

            # Save Kubernetes YAML files
            k8s_dir = output_dir / "kubernetes"
            k8s_dir.mkdir(exist_ok=True)

            crd_filename = f"{parsed_request.kind.lower()}-crd.yaml"
            crd_filepath = k8s_dir / crd_filename

            instance_filename = f"{parsed_request.kind.lower()}-instance.yaml"
            instance_filepath = k8s_dir / instance_filename

            combined_filename = f"{parsed_request.kind.lower()}-complete.yaml"
            combined_filepath = k8s_dir / combined_filename

            # Save YAML files
            with open(crd_filepath, 'w') as f:
                f.write(crd_yaml)

            with open(instance_filepath, 'w') as f:
                f.write(instance_yaml)

            with open(combined_filepath, 'w') as f:
                f.write(combined_yaml)

            # Display impressive results
            display_kubernetes_output(None, parsed_request, combined_yaml)

            console.print(f"\n[green]💾 Files saved to generated_specs/:[/green]")
            console.print(f"  📄 OpenAPI spec: {openapi_filepath}")
            console.print(f"  🏗️  CRD YAML: {crd_filepath}")
            console.print(f"  🎯 Instance YAML: {instance_filepath}")
            console.print(f"  📦 Complete YAML: {combined_filepath}")

            # Show output locations and usage
            console.print("\n[bold cyan]📁 Generated Files & Usage:[/bold cyan]")

            usage_table = Table(show_header=True, header_style="bold blue")
            usage_table.add_column("File", style="cyan")
            usage_table.add_column("Location", style="yellow")
            usage_table.add_column("Usage", style="green")

            usage_table.add_row(
                "📄 OpenAPI Spec",
                str(openapi_filepath),
                "MCP server generation"
            )
            usage_table.add_row(
                "🏗️  CRD YAML",
                str(crd_filepath),
                "kubectl apply -f"
            )
            usage_table.add_row(
                "🎯 Instance YAML",
                str(instance_filepath),
                "kubectl apply -f"
            )
            usage_table.add_row(
                "📦 Complete YAML",
                str(combined_filepath),
                "kubectl apply -f"
            )
            usage_table.add_row(
                "🤖 Controller Code",
                "Use openapi-mcp-codegen",
                "K8s operator development"
            )

            console.print(usage_table)

            console.print("\n[bold yellow]🚀 Real-World Applications:[/bold yellow]")
            console.print("• [green]Platform Engineering[/green] - Build internal Kubernetes platforms")
            console.print("• [blue]Service Mesh Integration[/blue] - Create custom service APIs")
            console.print("• [cyan]DevOps Automation[/cyan] - Automate infrastructure management")
            console.print("• [magenta]Multi-tenant Systems[/magenta] - Tenant-specific resource management")

            console.print("\n[bold green]🔧 Development Workflow:[/bold green]")
            console.print(f"1. 📝 AI generated OpenAPI spec: {openapi_filepath}")
            console.print(f"2. 🏗️  Deploy CRD: kubectl apply -f {crd_filepath}")
            console.print(f"3. 🚀 Deploy instance: kubectl apply -f {instance_filepath}")
            console.print(f"4. 🎯 Or deploy all at once: kubectl apply -f {combined_filepath}")
            console.print("5. 📊 Monitor your new API: kubectl get redisclusters")

        except Exception as e:
            console.print(f"[red]❌ Error: {e}[/red]")

    except KeyboardInterrupt:
        console.print("\n[yellow]👋 Demo cancelled[/yellow]")
    except EOFError:
        console.print("\n[yellow]👋 Goodbye![/yellow]")

def main():
    """Main demo function"""
    console.clear()
    interactive_demo()

if __name__ == "__main__":
    main()