#!/usr/bin/env python3
"""
Impressive AI-Powered Kubernetes Extension Generator Demo
This demo showcases the full power of AI-driven API generation with real Kubernetes outputs.
"""

import os
import json
import time
import yaml
from pathlib import Path
from typing import Dict, Any

# Add the src directory to the path
import sys
sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from ai_platform_generator.agent import PlatformExtensionAgent, CodegenRequest
from ai_platform_generator.codegen import CodeGenerator
from ai_platform_generator.cluster_manager import KindClusterManager, ClusterStatus, DeploymentStatus
from rich.console import Console
from rich.panel import Panel
from rich.table import Table
from rich.syntax import Syntax
from rich.progress import Progress, SpinnerColumn, TextColumn
from rich.layout import Layout
from rich.align import Align
from rich import print as rprint

console = Console()

def print_banner():
    """Print impressive banner"""
    banner = """
[bold cyan]
╔══════════════════════════════════════════════════════════════╗
║                🚀 AI KUBERNETES API GENERATOR 🚀               ║
║                                                              ║
║  Transform natural language into production Kubernetes      ║
║  Custom Resources, APIs, and Controllers in seconds!        ║
╚══════════════════════════════════════════════════════════════╝
[/bold cyan]
"""
    rprint(banner)

def display_processing_animation():
    """Show AI processing animation"""
    with Progress(
        SpinnerColumn(),
        TextColumn("[progress.description]{task.description}"),
        console=console,
        transient=True,
    ) as progress:
        task = progress.add_task("[cyan]🤖 AI analyzing your request...", total=None)
        time.sleep(1)

        progress.update(task, description="[cyan]🧠 Understanding Kubernetes requirements...")
        time.sleep(1)

        progress.update(task, description="[cyan]⚡ Generating OpenAPI specification...")
        time.sleep(1)

        progress.update(task, description="[cyan]🏗️  Creating Kubernetes CRD definitions...")
        time.sleep(1)

        progress.update(task, description="[cyan]📝 Building Controller templates...")
        time.sleep(1)

def display_kubernetes_output(api_result: Dict[str, Any], request: CodegenRequest, yaml_content: str = None):
    """Display impressive Kubernetes outputs"""

    # Create impressive output layout
    layout = Layout()
    layout.split_column(
        Layout(name="header", size=5),
        Layout(name="main"),
        Layout(name="footer", size=3)
    )

    # Header
    header_content = f"[bold green]✅ Successfully Generated: {request.kind} Kubernetes API[/bold green]"
    layout["header"].update(Align.center(Panel(header_content, style="green")))

    # Main content with tabs
    layout["main"].split_row(
        Layout(name="info", size=40),
        Layout(name="code")
    )

    # Info panel
    info_table = Table(title=f"📋 {request.kind} API Details", show_header=False)
    info_table.add_column("Property", style="cyan")
    info_table.add_column("Value", style="white")

    info_table.add_row("🏷️  API Group", request.group)
    info_table.add_row("🔢 Version", request.version)
    info_table.add_row("🎯 Kind", request.kind)
    info_table.add_row("📊 Spec Fields", str(len(request.spec_properties)))

    for field_name, field_info in request.spec_properties.items():
        field_type = field_info.get("type", "string") if isinstance(field_info, dict) else field_info
        info_table.add_row(f"  • {field_name}", f"[yellow]{field_type}[/yellow]")

    layout["info"].update(Panel(info_table, border_style="blue"))

    # Code panel with Kubernetes YAML
    if yaml_content:
        k8s_yaml = yaml_content
    else:
        _, _, k8s_yaml = generate_impressive_k8s_yaml(request)
    syntax = Syntax(k8s_yaml, "yaml", theme="monokai", line_numbers=True)
    layout["code"].update(Panel(syntax, title=f"📄 Generated Kubernetes YAML", border_style="green"))

    layout["footer"].update(Align.center("[dim]💡 Generated by AI - Ready for production deployment[/dim]"))

    console.print(layout)

def generate_impressive_k8s_yaml(request: CodegenRequest) -> tuple[str, str, str]:
    """Generate impressive Kubernetes YAML with multiple resources using robust CRD generation
    Returns: (crd_yaml, instance_yaml, combined_yaml)
    """

    # Build CRD structure with robust array handling
    crd_dict = {
        "apiVersion": "apiextensions.k8s.io/v1",
        "kind": "CustomResourceDefinition",
        "metadata": {
            "name": f"{request.kind.lower()}s.{request.group}",
            "annotations": {
                "cert-manager.io/inject-ca-from": f"{request.group.split('.')[0]}/{request.kind.lower()}-serving-cert"
            }
        },
        "spec": {
            "group": request.group,
            "versions": [{
                "name": request.version,
                "served": True,
                "storage": True,
                "schema": {
                    "openAPIV3Schema": {
                        "type": "object",
                        "properties": {
                            "apiVersion": {
                                "type": "string"
                            },
                            "kind": {
                                "type": "string"
                            },
                            "metadata": {
                                "type": "object"
                            },
                            "spec": {
                                "type": "object",
                                "properties": {}
                            }
                        }
                    }
                }
            }],
            "names": {
                "kind": request.kind,
                "plural": f"{request.kind.lower()}s",
                "singular": request.kind.lower()
            },
            "scope": "Namespaced"
        }
    }

    # Add spec properties with guaranteed proper array handling
    for field_name, field_info in request.spec_properties.items():
        field_type = field_info.get("type", "string") if isinstance(field_info, dict) else field_info
        field_desc = field_info.get("description", f"Description for {field_name}")

        property_schema = {
            "type": field_type,
            "description": field_desc
        }

        # CRITICAL FIX: Always add items schema for array types
        if field_type == "array":
            property_schema["items"] = {
                "type": "string",
                "description": f"Array item for {field_name}"
            }
        elif field_type == "object":
            # CRITICAL FIX: Objects must have properties defined in OpenAPI v3 schema
            property_schema["properties"] = {
                "key": {
                    "type": "string",
                    "description": f"Configuration key for {field_name}"
                },
                "value": {
                    "type": "string",
                    "description": f"Configuration value for {field_name}"
                }
            }
            # Allow additional properties for flexibility
            property_schema["additionalProperties"] = {
                "type": "string"
            }

        crd_dict["spec"]["versions"][0]["schema"]["openAPIV3Schema"]["properties"]["spec"]["properties"][field_name] = property_schema

    # Generate Sample Instance
    sample_spec = {}
    for field_name, field_info in request.spec_properties.items():
        field_type = field_info.get("type", "string") if isinstance(field_info, dict) else field_info

        if field_type == "string":
            sample_spec[field_name] = "example-value"
        elif field_type == "integer":
            sample_spec[field_name] = 3
        elif field_type == "boolean":
            sample_spec[field_name] = True
        elif field_type == "array":
            sample_spec[field_name] = ["item1", "item2", "item3"]
        elif field_type == "object":
            # CRITICAL FIX: Object instances must match the object schema
            sample_spec[field_name] = {
                "key": "example-key",
                "value": "example-value"
            }
        else:
            sample_spec[field_name] = "example-value"

    # Create instance structure
    instance_dict = {
        "apiVersion": f"{request.group}/{request.version}",
        "kind": request.kind,
        "metadata": {
            "name": f"my-{request.kind.lower()}-instance",
            "namespace": "default"
        },
        "spec": sample_spec
    }

    # Convert to YAML strings with proper formatting
    crd_yaml = yaml.dump(crd_dict, default_flow_style=False, sort_keys=False)
    instance_yaml = yaml.dump(instance_dict, default_flow_style=False, sort_keys=False)
    combined_yaml = crd_yaml + "---\n" + instance_yaml

    return crd_yaml, instance_yaml, combined_yaml

def interactive_demo():
    """Run impressive interactive demo"""
    print_banner()

    # Initialize variables with default values to prevent scoping issues
    openapi_filepath = None
    crd_filepath = None
    instance_filepath = None
    combined_filepath = None

    # Check API configuration
    api_key = os.getenv("OPENROUTER_API_KEY")
    model = os.getenv("OPENROUTER_MODEL", "deepseek/deepseek-chat-v3.1:free")

    if not api_key:
        console.print("[red]❌ OPENROUTER_API_KEY not set![/red]")
        console.print("[yellow]Please set your OpenRouter API key:[/yellow]")
        console.print("export OPENROUTER_API_KEY=\"your-key-here\"")
        console.print("\n[green]🔄 Running in DEMO MODE with sample data...[/green]")
        run_demo_mode()
        return

    console.print(f"[green]✅ OpenRouter API configured[/green]")
    console.print(f"[blue]🧠 Using model: {model}[/blue]")
    console.print()

    # Example requests to show off
    examples = [
        "Create a Kubernetes API for managing Redis clusters with memory, CPU, and persistence settings",
        "I need a Database service API with connection strings, backup schedules, and auto-scaling",
        "Build a Monitoring service API for collecting metrics with intervals and retention policies",
        "Create a Cache service API with eviction policies, memory limits, and cluster configuration"
    ]

    console.print("[bold cyan]🎯 Choose an example or create your own:[/bold cyan]")
    for i, example in enumerate(examples, 1):
        console.print(f"[cyan]{i}.[/cyan] {example}")
    console.print("[cyan]5.[/cyan] [yellow]Custom request...[/yellow]")

    try:
        choice = input("\nEnter choice (1-5): ").strip()

        if choice == "5":
            user_request = input("\n📝 Describe your Kubernetes API: ").strip()
        elif choice in ["1", "2", "3", "4"]:
            user_request = examples[int(choice) - 1]
        else:
            console.print("[red]Invalid choice![/red]")
            return

        if not user_request:
            return

        console.print(f"\n[bold]🚀 Processing: {user_request}[/bold]")

        # Show processing animation
        display_processing_animation()

        # Process with AI - Enhanced error handling for initialization
        try:
            # Initialize agent with SSL verification disabled for demo environments
            agent = PlatformExtensionAgent(api_key=api_key, model=model, verify_ssl=False)

            # Check if agent is available
            if not agent.is_available():
                console.print(f"[yellow]⚠️  {agent.get_error_message()}[/yellow]")
                console.print("[yellow]🔄 Running in DEMO MODE with intelligent sample data...[/yellow]")
                run_demo_mode_with_request(user_request)
                return

            console.print("[cyan]🤖 AI is generating your Kubernetes API...[/cyan]")
            parsed_request = agent.parse_request(user_request)

            # Generate and save all results
            output_dir = Path("generated_specs")
            output_dir.mkdir(exist_ok=True)

            # Generate OpenAPI spec
            codegen = CodeGenerator()
            openapi_spec = codegen.generate_openapi_spec(parsed_request)

            # Generate Kubernetes YAML files
            crd_yaml, instance_yaml, combined_yaml = generate_impressive_k8s_yaml(parsed_request)

            # Save OpenAPI specification
            openapi_filename = f"{parsed_request.kind.lower()}_demo.json"
            openapi_filepath = output_dir / openapi_filename

            with open(openapi_filepath, 'w') as f:
                json.dump(openapi_spec, f, indent=2)

            # Save Kubernetes YAML files
            k8s_dir = output_dir / "kubernetes"
            k8s_dir.mkdir(exist_ok=True)

            crd_filename = f"{parsed_request.kind.lower()}-crd.yaml"
            crd_filepath = k8s_dir / crd_filename

            instance_filename = f"{parsed_request.kind.lower()}-instance.yaml"
            instance_filepath = k8s_dir / instance_filename

            combined_filename = f"{parsed_request.kind.lower()}-complete.yaml"
            combined_filepath = k8s_dir / combined_filename

            # Save YAML files
            with open(crd_filepath, 'w') as f:
                f.write(crd_yaml)

            with open(instance_filepath, 'w') as f:
                f.write(instance_yaml)

            with open(combined_filepath, 'w') as f:
                f.write(combined_yaml)

            # Display impressive results
            display_kubernetes_output(None, parsed_request, combined_yaml)

            console.print(f"\n[green]💾 Files saved to generated_specs/:[/green]")
            console.print(f"  📄 OpenAPI spec: {openapi_filepath}")
            console.print(f"  🏗️  CRD YAML: {crd_filepath}")
            console.print(f"  🎯 Instance YAML: {instance_filepath}")
            console.print(f"  📦 Complete YAML: {combined_filepath}")

            # Show output locations and usage
            console.print("\n[bold cyan]📁 Generated Files & Usage:[/bold cyan]")

            usage_table = Table(show_header=True, header_style="bold blue")
            usage_table.add_column("File", style="cyan")
            usage_table.add_column("Location", style="yellow")
            usage_table.add_column("Usage", style="green")

            usage_table.add_row(
                "📄 OpenAPI Spec",
                str(openapi_filepath),
                "MCP server generation"
            )
            usage_table.add_row(
                "🏗️  CRD YAML",
                str(crd_filepath),
                "kubectl apply -f"
            )
            usage_table.add_row(
                "🎯 Instance YAML",
                str(instance_filepath),
                "kubectl apply -f"
            )
            usage_table.add_row(
                "📦 Complete YAML",
                str(combined_filepath),
                "kubectl apply -f"
            )
            usage_table.add_row(
                "🤖 Controller Code",
                "Use openapi-mcp-codegen",
                "K8s operator development"
            )

            console.print(usage_table)

            console.print("\n[bold yellow]🚀 Real-World Applications:[/bold yellow]")
            console.print("• [green]Platform Engineering[/green] - Build internal Kubernetes platforms")
            console.print("• [blue]Service Mesh Integration[/blue] - Create custom service APIs")
            console.print("• [cyan]DevOps Automation[/cyan] - Automate infrastructure management")
            console.print("• [magenta]Multi-tenant Systems[/magenta] - Tenant-specific resource management")

            console.print("\n[bold green]🔧 Development Workflow:[/bold green]")
            console.print(f"1. 📝 AI generated OpenAPI spec: {openapi_filepath}")
            console.print(f"2. 🏗️  Deploy CRD: kubectl apply -f {crd_filepath}")
            console.print(f"3. 🚀 Deploy instance: kubectl apply -f {instance_filepath}")
            console.print(f"4. 🎯 Or deploy all at once: kubectl apply -f {combined_filepath}")
            console.print("5. 📊 Monitor your new API: kubectl get redisclusters")

        except Exception as e:
            console.print(f"[red]❌ Error initializing AI service: {e}[/red]")
            console.print("[yellow]🔄 Running in DEMO MODE with intelligent sample data...[/yellow]")
            run_demo_mode_with_request(user_request)

        # Only try deployment if files were successfully created
        if openapi_filepath and crd_filepath and instance_filepath:
            try_deploy_to_cluster(openapi_filepath, crd_filepath, instance_filepath, combined_filepath, parsed_request)

    except KeyboardInterrupt:
        console.print("\n[yellow]👋 Demo cancelled[/yellow]")
    except EOFError:
        console.print("\n[yellow]👋 Goodbye![/yellow]")

def run_demo_mode():
    """Run demo mode with predefined sample data"""
    demo_request = "Create a Redis cluster API with memory, CPU, and persistence settings"
    run_demo_mode_with_request(demo_request)

def run_demo_mode_with_request(user_request: str):
    """Run demo mode with sample data based on user request"""
    console.print("\n[bold yellow]🔄 DEMO MODE - Sample Kubernetes API Generation[/bold yellow]")

    # Create sample request based on common patterns
    if "redis" in user_request.lower():
        sample_request = CodegenRequest(
            group="database.cnoe.io",
            version="v1alpha1",
            kind="RedisCluster",
            spec_properties={
                "memory": {"type": "string", "description": "Memory limit for Redis cluster"},
                "cpu": {"type": "string", "description": "CPU request for Redis cluster"},
                "persistence": {"type": "boolean", "description": "Enable persistent storage"},
                "replicas": {"type": "integer", "description": "Number of Redis replicas"}
            },
            description="Redis cluster management API for Kubernetes platform"
        )
    elif "database" in user_request.lower():
        sample_request = CodegenRequest(
            group="database.cnoe.io",
            version="v1alpha1",
            kind="DatabaseService",
            spec_properties={
                "connectionString": {"type": "string", "description": "Database connection string"},
                "backupSchedule": {"type": "string", "description": "Cron schedule for backups"},
                "autoScaling": {"type": "boolean", "description": "Enable auto-scaling"}
            },
            description="Database service management API"
        )
    elif "monitoring" in user_request.lower():
        sample_request = CodegenRequest(
            group="monitoring.cnoe.io",
            version="v1alpha1",
            kind="MonitoringService",
            spec_properties={
                "interval": {"type": "string", "description": "Metrics collection interval"},
                "retention": {"type": "string", "description": "Data retention period"},
                "endpoints": {"type": "array", "description": "Monitoring endpoints"}
            },
            description="Monitoring service configuration API"
        )
    else:
        # Generic sample
        sample_request = CodegenRequest(
            group="platform.cnoe.io",
            version="v1alpha1",
            kind="CustomResource",
            spec_properties={
                "name": {"type": "string", "description": "Resource name"},
                "enabled": {"type": "boolean", "description": "Enable resource"},
                "config": {"type": "object", "description": "Configuration settings"}
            },
            description="Sample custom resource API"
        )

    try:
        # Generate and save all results
        output_dir = Path("generated_specs")
        output_dir.mkdir(exist_ok=True)

        # Generate OpenAPI spec
        codegen = CodeGenerator()
        openapi_spec = codegen.generate_openapi_spec(sample_request)

        # Generate Kubernetes YAML files
        crd_yaml, instance_yaml, combined_yaml = generate_impressive_k8s_yaml(sample_request)

        # Save OpenAPI specification
        openapi_filename = f"{sample_request.kind.lower()}_demo.json"
        openapi_filepath = output_dir / openapi_filename

        with open(openapi_filepath, 'w') as f:
            json.dump(openapi_spec, f, indent=2)

        # Save Kubernetes YAML files
        k8s_dir = output_dir / "kubernetes"
        k8s_dir.mkdir(exist_ok=True)

        crd_filename = f"{sample_request.kind.lower()}-crd.yaml"
        crd_filepath = k8s_dir / crd_filename

        instance_filename = f"{sample_request.kind.lower()}-instance.yaml"
        instance_filepath = k8s_dir / instance_filename

        combined_filename = f"{sample_request.kind.lower()}-complete.yaml"
        combined_filepath = k8s_dir / combined_filename

        # Save YAML files
        with open(crd_filepath, 'w') as f:
            f.write(crd_yaml)

        with open(instance_filepath, 'w') as f:
            f.write(instance_yaml)

        with open(combined_filepath, 'w') as f:
            f.write(combined_yaml)

        # Display impressive results
        display_kubernetes_output(None, sample_request, combined_yaml)

        console.print(f"\n[green]💾 Demo files saved to generated_specs/:[/green]")
        console.print(f"  📄 OpenAPI spec: {openapi_filepath}")
        console.print(f"  🏗️  CRD YAML: {crd_filepath}")
        console.print(f"  🎯 Instance YAML: {instance_filepath}")
        console.print(f"  📦 Complete YAML: {combined_filepath}")

        console.print("\n[bold green]✨ Demo Mode Complete! ✨[/bold green]")
        console.print("[yellow]To use real AI generation, please configure your OpenRouter API key.[/yellow]")

    except Exception as e:
        console.print(f"[red]❌ Demo mode failed: {e}[/red]")

def main():
    """Main demo function"""
    console.clear()
    interactive_demo()

def try_deploy_to_cluster(openapi_filepath, crd_filepath, instance_filepath, combined_filepath, request: CodegenRequest):
    """Automatically deploy resources to a Kind cluster with graceful error handling."""
    console.print("\n" + "="*60)
    console.print("[bold yellow]🚀 Attempting Kubernetes Cluster Deployment...[/bold yellow]")
    console.print("="*60)

    try:
        deploy_to_kind_cluster(crd_filepath, instance_filepath, request)
    except Exception as e:
        console.print(f"\n[yellow]⚠️  Cluster deployment failed: {str(e)}[/yellow]")
        console.print("[yellow]💡 This is normal in environments without Docker or Kind support[/yellow]")
        console.print("[green]✅ Your Kubernetes resources were generated successfully and are ready for manual deployment![/green]")

        console.print("\n[bold cyan]📁 Manual Deployment Instructions:[/bold cyan]")
        console.print(f"[blue]1. Deploy CRD: kubectl apply -f {crd_filepath}[/blue]")
        console.print(f"[blue]2. Deploy instance: kubectl apply -f {instance_filepath}[/blue]")
        console.print(f"[blue]3. Or deploy all: kubectl apply -f {combined_filepath}[/blue]")

def deploy_to_kind_cluster(crd_filepath, instance_filepath, request: CodegenRequest):
    """Deploy resources to a Kind cluster with visual feedback and error handling."""
    console.print("\n[bold cyan]🚀 Starting Kubernetes Cluster Deployment...[/bold cyan]")

    try:
        cluster_manager = KindClusterManager()

        # Check prerequisites
        with Progress(
            SpinnerColumn(),
            TextColumn("[progress.description]{task.description}"),
            console=console,
            transient=True,
        ) as progress:
            task = progress.add_task("[cyan]🔍 Checking prerequisites...", total=None)

            prerequisites_ok, issues = cluster_manager.check_prerequisites()

            if not prerequisites_ok:
                console.print("[red]❌ Missing prerequisites:[/red]")
                for issue in issues:
                    console.print(f"   • {issue}")
                console.print("\n[yellow]💡 This is normal in codespace or restricted environments[/yellow]")
                console.print("[yellow]💡 Your Kubernetes YAML files are ready for manual deployment[/yellow]")
                raise Exception(f"Missing prerequisites: {'; '.join(issues)}")

            progress.update(task, description="[green]✅ Prerequisites checked!")

            # Check cluster status
            progress.update(task, description="[cyan]🏗️  Checking Kind cluster status...")
            cluster_status = cluster_manager.get_cluster_status()

            if not cluster_status.exists:
                progress.update(task, description="[cyan]🏗️  Creating Kind cluster...")
                success, message = cluster_manager.create_cluster()
                if not success:
                    console.print(f"[red]❌ Failed to create cluster: {message}[/red]")
                    raise Exception(f"Cluster creation failed: {message}")
                console.print("[green]✅ Kind cluster created successfully![/green]")
            elif not cluster_status.running:
                console.print("[yellow]⚠️  Cluster exists but may not be ready[/yellow]")
                if not cluster_status.kubectl_accessible:
                    console.print("[red]❌ Cluster is not accessible via kubectl[/red]")
                    raise Exception("Cluster exists but is not accessible")
            else:
                console.print("[green]✅ Kind cluster is running![/green]")

            # Deploy resources
            progress.update(task, description="[cyan]🚀 Deploying Kubernetes resources...")
            instance_name = f"my-{request.kind.lower()}-instance"

            success, message = cluster_manager.deploy_resources(
                str(crd_filepath),
                str(instance_filepath),
                request.kind
            )

            if not success:
                console.print(f"[red]❌ Deployment failed: {message}[/red]")
                raise Exception(f"Resource deployment failed: {message}")

            console.print("[green]✅ Resources deployed to cluster![/green]")

            # Verify deployment
            progress.update(task, description="[cyan]🔍 Verifying deployment...")
            time.sleep(2)  # Give resources time to register

            deployment_status = cluster_manager.verify_deployment(request.kind, instance_name)

            # Display deployment results
            display_deployment_results(deployment_status, cluster_manager, request.kind, instance_name)

    except Exception as e:
        # Re-raise to be handled by the caller
        raise e

def display_deployment_results(status: DeploymentStatus, cluster_manager: KindClusterManager, resource_kind: str, instance_name: str):
    """Display impressive deployment results."""

    console.print("\n" + "="*60)
    console.print("[bold green]🎉 Deployment Results![/bold green]")
    console.print("="*60)

    # Create results table
    results_table = Table(title="📊 Resource Status", show_header=True)
    results_table.add_column("Component", style="cyan")
    results_table.add_column("Status", style="white")
    results_table.add_column("Details", style="yellow")

    results_table.add_row(
        "🏗️  Custom Resource Definition",
        "✅ Applied" if status.crd_applied else "❌ Failed",
        f"{instance_name}s.cnoe.io"
    )
    results_table.add_row(
        "🎯 Resource Instance",
        "✅ Applied" if status.instance_applied else "❌ Failed",
        instance_name
    )
    results_table.add_row(
        "📡 API Accessibility",
        "✅ Ready" if status.resource_accessible else "❌ Not Ready",
        f"kubectl get {resource_kind.lower()}s"
    )
    if status.resource_status:
        results_table.add_row(
            "📈 Current Status",
            status.resource_status,
            "Live cluster status"
        )

    console.print(results_table)

    # Show next steps
    console.print("\n[bold cyan]🎯 Next Commands:[/bold cyan]")
    console.print(f"[green]# View your new resource:[/green]")
    console.print(f"[blue]kubectl get {resource_kind.lower()}s --context kind-ai-platform-demo[/blue]")
    console.print(f"[green]# Get detailed info:[/green]")
    console.print(f"[blue]kubectl describe {resource_kind.lower()} {instance_name} --context kind-ai-platform-demo[/blue]")
    console.print(f"[green]# View cluster nodes:[/green]")
    console.print("[blue]kubectl get nodes --context kind-ai-platform-demo[/blue]")
    console.print(f"[green]# Delete cluster when done:[/green]")
    console.print("[blue]kind delete cluster --name ai-platform-demo[/blue]")

    # Show cluster info
    cluster_status = cluster_manager.get_cluster_status()
    console.print(f"\n[dim]💡 Cluster: {cluster_status.name} | Nodes: {len(cluster_status.nodes)} | Context: kind-{cluster_status.name}[/dim]")

if __name__ == "__main__":
    main()