// Code generated by ai-platform-generator. DO NOT EDIT.
// Regenerate via: ai-platform-generator generate ...

// Package v1alpha1 contains API Schema definitions for the
// ai.platform.cnoe.io v1alpha1 API group.
// +kubebuilder:object:generate=true
// +groupName=ai.platform.cnoe.io
package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"sigs.k8s.io/controller-runtime/pkg/scheme"
)

// GroupVersion is the API GroupVersion used to register these objects.
var GroupVersion = metav1.GroupVersion{Group: "ai.platform.cnoe.io", Version: "v1alpha1"}

// SchemeBuilder is used to add go types to the GroupVersionKind scheme.
var SchemeBuilder = &scheme.Builder{GroupVersion: schemaGV()}

// AddToScheme registers this API group's types with a scheme.
var AddToScheme = SchemeBuilder.AddToScheme

func schemaGV() runtime.GroupVersioner {
	return runtime.GroupVersioner(metav1.GroupVersion{
		Group:   "ai.platform.cnoe.io",
		Version: "v1alpha1",
	})
}

// MLPipelineSpec defines the desired state of MLPipeline.
type MLPipelineSpec struct {
	// Whether GPU-backed nodes are used.
	// +kubebuilder:validation:Required
	GpuEnabled bool `json:"gpuEnabled"`
	// Maximum number of stages to run concurrently.
	// +kubebuilder:validation:Required
	Parallelism int32 `json:"parallelism"`
	// Ordered list of pipeline stage names.
	// +kubebuilder:validation:Required
	Stages []string `json:"stages"`
}

// MLPipelineStatus defines the observed state of MLPipeline.
type MLPipelineStatus struct {
	// ObservedGeneration is the most recent .metadata.generation reconciled
	// by the controller.
	ObservedGeneration int64 `json:"observedGeneration,omitempty"`

	// Conditions represent the latest available observations of the
	// resource's state.
	// +patchMergeKey=type
	// +patchStrategy=merge
	Conditions []metav1.Condition `json:"conditions,omitempty" patchMergeKey:"type" patchStrategy:"merge"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status

// MLPipeline is the Schema for the mlpipelines API.
type MLPipeline struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   MLPipelineSpec   `json:"spec,omitempty"`
	Status MLPipelineStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// MLPipelineList contains a list of MLPipeline.
type MLPipelineList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []MLPipeline `json:"items"`
}

func init() {
	SchemeBuilder.Register(&MLPipeline{}, &MLPipelineList{})
}
