// Code generated by ai-platform-generator. DO NOT EDIT.
// Regenerate via: ai-platform-generator generate ...

// Package v1alpha1 contains API Schema definitions for the
// database.cnoe.io v1alpha1 API group.
// +kubebuilder:object:generate=true
// +groupName=database.cnoe.io
package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"sigs.k8s.io/controller-runtime/pkg/scheme"
)

// GroupVersion is the API GroupVersion used to register these objects.
var GroupVersion = metav1.GroupVersion{Group: "database.cnoe.io", Version: "v1alpha1"}

// SchemeBuilder is used to add go types to the GroupVersionKind scheme.
var SchemeBuilder = &scheme.Builder{GroupVersion: schemaGV()}

// AddToScheme registers this API group's types with a scheme.
var AddToScheme = SchemeBuilder.AddToScheme

func schemaGV() runtime.GroupVersioner {
	return runtime.GroupVersioner(metav1.GroupVersion{
		Group:   "database.cnoe.io",
		Version: "v1alpha1",
	})
}

// DatabaseBackupSpec defines the desired state of DatabaseBackup.
type DatabaseBackupSpec struct {
	// Whether this backup schedule is active.
	// +kubebuilder:validation:Required
	Enabled bool `json:"enabled"`
	// How long to retain backups, in days.
	// +kubebuilder:validation:Required
	RetentionDays int32 `json:"retentionDays"`
	// Cron expression controlling when the backup job runs.
	// +kubebuilder:validation:Required
	Schedule string `json:"schedule"`
}

// DatabaseBackupStatus defines the observed state of DatabaseBackup.
type DatabaseBackupStatus struct {
	// ObservedGeneration is the most recent .metadata.generation reconciled
	// by the controller.
	ObservedGeneration int64 `json:"observedGeneration,omitempty"`

	// Conditions represent the latest available observations of the
	// resource's state.
	// +patchMergeKey=type
	// +patchStrategy=merge
	Conditions []metav1.Condition `json:"conditions,omitempty" patchMergeKey:"type" patchStrategy:"merge"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status

// DatabaseBackup is the Schema for the databasebackups API.
type DatabaseBackup struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   DatabaseBackupSpec   `json:"spec,omitempty"`
	Status DatabaseBackupStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// DatabaseBackupList contains a list of DatabaseBackup.
type DatabaseBackupList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []DatabaseBackup `json:"items"`
}

func init() {
	SchemeBuilder.Register(&DatabaseBackup{}, &DatabaseBackupList{})
}
