// Code generated by ai-platform-generator. DO NOT EDIT.
// Regenerate via: ai-platform-generator generate ...

// Package v1alpha1 contains API Schema definitions for the
// cache.cnoe.io v1alpha1 API group.
// +kubebuilder:object:generate=true
// +groupName=cache.cnoe.io
package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"sigs.k8s.io/controller-runtime/pkg/scheme"
)

// GroupVersion is the API GroupVersion used to register these objects.
var GroupVersion = metav1.GroupVersion{Group: "cache.cnoe.io", Version: "v1alpha1"}

// SchemeBuilder is used to add go types to the GroupVersionKind scheme.
var SchemeBuilder = &scheme.Builder{GroupVersion: schemaGV()}

// AddToScheme registers this API group's types with a scheme.
var AddToScheme = SchemeBuilder.AddToScheme

func schemaGV() runtime.GroupVersioner {
	return runtime.GroupVersioner(metav1.GroupVersion{
		Group:   "cache.cnoe.io",
		Version: "v1alpha1",
	})
}

// RedisClusterSpec defines the desired state of RedisCluster.
type RedisClusterSpec struct {
	// Memory budget per node, in GiB.
	// +kubebuilder:validation:Required
	MemoryGiB int32 `json:"memoryGiB"`
	// Whether AOF persistence is enabled.
	// +kubebuilder:validation:Required
	Persistence bool `json:"persistence"`
	// TCP port the Redis cluster listens on.
	// +kubebuilder:validation:Required
	Port int32 `json:"port"`
}

// RedisClusterStatus defines the observed state of RedisCluster.
type RedisClusterStatus struct {
	// ObservedGeneration is the most recent .metadata.generation reconciled
	// by the controller.
	ObservedGeneration int64 `json:"observedGeneration,omitempty"`

	// Conditions represent the latest available observations of the
	// resource's state.
	// +patchMergeKey=type
	// +patchStrategy=merge
	Conditions []metav1.Condition `json:"conditions,omitempty" patchMergeKey:"type" patchStrategy:"merge"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status

// RedisCluster is the Schema for the redisclusters API.
type RedisCluster struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   RedisClusterSpec   `json:"spec,omitempty"`
	Status RedisClusterStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RedisClusterList contains a list of RedisCluster.
type RedisClusterList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []RedisCluster `json:"items"`
}

func init() {
	SchemeBuilder.Register(&RedisCluster{}, &RedisClusterList{})
}
