#!/usr/bin/env python3
"""
AI Scaffolding Agent for OpenAPI MCP Code Generation

This agent translates natural language descriptions of APIs into the proper
OpenAPI specifications and configuration files needed by openapi-mcp-codegen.
"""

import os
import json
import yaml
import subprocess
import tempfile
import shutil
from pathlib import Path
from typing import Dict, List, Optional, Any
import logging
from dataclasses import dataclass
from abc import ABC, abstractmethod

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


@dataclass
class APIEndpoint:
    """Represents a single API endpoint"""
    path: str
    method: str
    operation_id: str
    summary: str
    description: str
    parameters: List[Dict[str, Any]]
    request_body: Optional[Dict[str, Any]]
    responses: Dict[str, Any]


@dataclass
class APISchema:
    """Represents an API schema/model"""
    name: str
    properties: Dict[str, Any]
    required: List[str]
    description: str


@dataclass
class APIInfo:
    """Basic API information"""
    title: str
    description: str
    version: str
    base_url: str


class OpenAPIGenerator:
    """Generates OpenAPI specifications from parsed natural language"""

    def __init__(self):
        self.api_info: Optional[APIInfo] = None
        self.schemas: List[APISchema] = []
        self.endpoints: List[APIEndpoint] = []

    def create_basic_openapi_spec(self, info: APIInfo) -> Dict[str, Any]:
        """Create a basic OpenAPI 3.0 specification"""
        return {
            "openapi": "3.0.4",
            "info": {
                "title": info.title,
                "description": info.description,
                "version": info.version
            },
            "servers": [
                {
                    "url": info.base_url,
                    "description": "Base API server"
                }
            ],
            "paths": {},
            "components": {
                "schemas": {}
            }
        }

    def add_schema(self, schema: APISchema) -> None:
        """Add a schema to the OpenAPI spec"""
        self.schemas.append(schema)

    def add_endpoint(self, endpoint: APIEndpoint) -> None:
        """Add an endpoint to the OpenAPI spec"""
        self.endpoints.append(endpoint)

    def generate_spec(self) -> Dict[str, Any]:
        """Generate the complete OpenAPI specification"""
        if not self.api_info:
            raise ValueError("API info must be set before generating spec")

        spec = self.create_basic_openapi_spec(self.api_info)

        # Add schemas
        for schema in self.schemas:
            spec["components"]["schemas"][schema.name] = {
                "type": "object",
                "properties": schema.properties,
                "required": schema.required,
                "description": schema.description
            }

        # Add endpoints
        for endpoint in self.endpoints:
            if endpoint.path not in spec["paths"]:
                spec["paths"][endpoint.path] = {}

            operation = {
                "operationId": endpoint.operation_id,
                "summary": endpoint.summary,
                "description": endpoint.description,
                "parameters": endpoint.parameters,
                "responses": endpoint.responses
            }

            if endpoint.request_body:
                operation["requestBody"] = endpoint.request_body

            spec["paths"][endpoint.path][endpoint.method.lower()] = operation

        return spec


class ConfigGenerator:
    """Generates configuration files for openapi-mcp-codegen"""

    def __init__(self):
        pass

    def create_config(self, title: str, description: str, author: str = "AI Agent") -> Dict[str, Any]:
        """Create a basic configuration for the MCP server"""
        return {
            "title": title.lower().replace(" ", "_"),
            "description": f"{description} MCP Server",
            "author": author,
            "email": "agent@cnoe.io",
            "version": "0.1.0",
            "license": "Apache-2.0",
            "python_version": "3.13.2",
            "headers": {
                "Accept": "application/json",
                "Content-Type": "application/json"
            },
            "poetry_dependencies": """
  python = ">=3.13,<4.0"
  httpx = ">=0.24.0"
  python-dotenv = ">=1.0.0"
  pydantic = ">=2.0.0"
  mcp = ">=1.9.0"
""".strip(),
            "file_headers": {
                "copyright": "Copyright 2025 CNOE",
                "license": "SPDX-License-Identifier: Apache-2.0",
                "message": "Generated by CNOE AI Scaffolding Agent"
            }
        }


class AIScaffoldingAgent:
    """Main AI scaffolding agent"""

    def __init__(self, openapi_codegen_path: Optional[str] = None):
        """
        Initialize the AI scaffolding agent

        Args:
            openapi_codegen_path: Path to the openapi-mcp-codegen executable
        """
        self.openapi_codegen_path = openapi_codegen_path or "python -m openapi_mcp_codegen"
        self.temp_dir = None

    def parse_natural_language_request(self, request: str) -> Dict[str, Any]:
        """
        Parse a natural language request into API components

        This is a simplified implementation that parses common patterns.
        In a production system, this would use an LLM for more sophisticated parsing.
        """
        request_lower = request.lower()

        # Try to extract API type and main entity
        if "pet store" in request_lower or "petstore" in request_lower:
            return self._parse_petstore_request(request)
        elif "user" in request_lower and "api" in request_lower:
            return self._parse_user_api_request(request)
        elif "blog" in request_lower or "post" in request_lower:
            return self._parse_blog_api_request(request)
        else:
            # Generic API parsing
            return self._parse_generic_api_request(request)

    def _parse_petstore_request(self, request: str) -> Dict[str, Any]:
        """Parse a petstore-style API request"""
        return {
            "info": APIInfo(
                title="Pet Store API",
                description="A simple pet store management API",
                version="1.0.0",
                base_url="/api/v1"
            ),
            "schemas": [
                APISchema(
                    name="Pet",
                    properties={
                        "id": {"type": "integer", "format": "int64"},
                        "name": {"type": "string"},
                        "category": {"$ref": "#/components/schemas/Category"},
                        "photoUrls": {"type": "array", "items": {"type": "string"}},
                        "tags": {"type": "array", "items": {"$ref": "#/components/schemas/Tag"}},
                        "status": {"type": "string", "enum": ["available", "pending", "sold"]}
                    },
                    required=["name", "photoUrls"],
                    description="A pet in the store"
                ),
                APISchema(
                    name="Category",
                    properties={
                        "id": {"type": "integer", "format": "int64"},
                        "name": {"type": "string"}
                    },
                    required=["id", "name"],
                    description="Category of a pet"
                ),
                APISchema(
                    name="Tag",
                    properties={
                        "id": {"type": "integer", "format": "int64"},
                        "name": {"type": "string"}
                    },
                    required=["id", "name"],
                    description="Tag for a pet"
                )
            ],
            "endpoints": [
                APIEndpoint(
                    path="/pets",
                    method="get",
                    operation_id="listPets",
                    summary="List all pets",
                    description="Returns a list of all pets in the store",
                    parameters=[],
                    request_body=None,
                    responses={
                        "200": {
                            "description": "A list of pets",
                            "content": {
                                "application/json": {
                                    "schema": {
                                        "type": "array",
                                        "items": {"$ref": "#/components/schemas/Pet"}
                                    }
                                }
                            }
                        }
                    }
                ),
                APIEndpoint(
                    path="/pets",
                    method="post",
                    operation_id="createPet",
                    summary="Create a new pet",
                    description="Creates a new pet in the store",
                    parameters=[],
                    request_body={
                        "required": True,
                        "content": {
                            "application/json": {
                                "schema": {"$ref": "#/components/schemas/Pet"}
                            }
                        }
                    },
                    responses={
                        "201": {
                            "description": "Pet created successfully",
                            "content": {
                                "application/json": {
                                    "schema": {"$ref": "#/components/schemas/Pet"}
                                }
                            }
                        }
                    }
                ),
                APIEndpoint(
                    path="/pets/{petId}",
                    method="get",
                    operation_id="getPetById",
                    summary="Get a pet by ID",
                    description="Returns a single pet by its ID",
                    parameters=[
                        {
                            "name": "petId",
                            "in": "path",
                            "required": True,
                            "schema": {"type": "integer", "format": "int64"},
                            "description": "ID of the pet to retrieve"
                        }
                    ],
                    request_body=None,
                    responses={
                        "200": {
                            "description": "Pet details",
                            "content": {
                                "application/json": {
                                    "schema": {"$ref": "#/components/schemas/Pet"}
                                }
                            }
                        },
                        "404": {
                            "description": "Pet not found"
                        }
                    }
                )
            ]
        }

    def _parse_user_api_request(self, request: str) -> Dict[str, Any]:
        """Parse a user management API request"""
        return {
            "info": APIInfo(
                title="User Management API",
                description="API for managing users",
                version="1.0.0",
                base_url="/api/v1"
            ),
            "schemas": [
                APISchema(
                    name="User",
                    properties={
                        "id": {"type": "integer", "format": "int64"},
                        "username": {"type": "string"},
                        "email": {"type": "string", "format": "email"},
                        "firstName": {"type": "string"},
                        "lastName": {"type": "string"},
                        "phone": {"type": "string"},
                        "userStatus": {"type": "integer", "description": "User Status"}
                    },
                    required=["username", "email"],
                    description="A user in the system"
                )
            ],
            "endpoints": [
                APIEndpoint(
                    path="/users",
                    method="get",
                    operation_id="listUsers",
                    summary="List all users",
                    description="Returns a list of all users",
                    parameters=[],
                    request_body=None,
                    responses={
                        "200": {
                            "description": "A list of users",
                            "content": {
                                "application/json": {
                                    "schema": {
                                        "type": "array",
                                        "items": {"$ref": "#/components/schemas/User"}
                                    }
                                }
                            }
                        }
                    }
                ),
                APIEndpoint(
                    path="/users",
                    method="post",
                    operation_id="createUser",
                    summary="Create a new user",
                    description="Creates a new user in the system",
                    parameters=[],
                    request_body={
                        "required": True,
                        "content": {
                            "application/json": {
                                "schema": {"$ref": "#/components/schemas/User"}
                            }
                        }
                    },
                    responses={
                        "201": {
                            "description": "User created successfully",
                            "content": {
                                "application/json": {
                                    "schema": {"$ref": "#/components/schemas/User"}
                                }
                            }
                        }
                    }
                )
            ]
        }

    def _parse_blog_api_request(self, request: str) -> Dict[str, Any]:
        """Parse a blog API request"""
        return {
            "info": APIInfo(
                title="Blog API",
                description="API for managing blog posts",
                version="1.0.0",
                base_url="/api/v1"
            ),
            "schemas": [
                APISchema(
                    name="Post",
                    properties={
                        "id": {"type": "integer", "format": "int64"},
                        "title": {"type": "string"},
                        "content": {"type": "string"},
                        "author": {"type": "string"},
                        "createdAt": {"type": "string", "format": "date-time"},
                        "updatedAt": {"type": "string", "format": "date-time"},
                        "published": {"type": "boolean"}
                    },
                    required=["title", "content", "author"],
                    description="A blog post"
                )
            ],
            "endpoints": [
                APIEndpoint(
                    path="/posts",
                    method="get",
                    operation_id="listPosts",
                    summary="List all posts",
                    description="Returns a list of all blog posts",
                    parameters=[],
                    request_body=None,
                    responses={
                        "200": {
                            "description": "A list of posts",
                            "content": {
                                "application/json": {
                                    "schema": {
                                        "type": "array",
                                        "items": {"$ref": "#/components/schemas/Post"}
                                    }
                                }
                            }
                        }
                    }
                )
            ]
        }

    def _parse_generic_api_request(self, request: str) -> Dict[str, Any]:
        """Parse a generic API request"""
        # Extract the main entity from the request
        words = request.split()
        entity = "Resource"
        for word in words:
            if word.lower() not in ["i", "want", "need", "create", "build", "api", "for", "a", "an", "the"]:
                entity = word.capitalize()
                break

        return {
            "info": APIInfo(
                title=f"{entity} API",
                description=f"API for managing {entity.lower()}s",
                version="1.0.0",
                base_url="/api/v1"
            ),
            "schemas": [
                APISchema(
                    name=entity,
                    properties={
                        "id": {"type": "integer", "format": "int64"},
                        "name": {"type": "string"}
                    },
                    required=["name"],
                    description=f"A {entity.lower()} in the system"
                )
            ],
            "endpoints": [
                APIEndpoint(
                    path=f"/{entity.lower()}s",
                    method="get",
                    operation_id=f"list{entity}s",
                    summary=f"List all {entity.lower()}s",
                    description=f"Returns a list of all {entity.lower()}s",
                    parameters=[],
                    request_body=None,
                    responses={
                        "200": {
                            "description": f"A list of {entity.lower()}s",
                            "content": {
                                "application/json": {
                                    "schema": {
                                        "type": "array",
                                        "items": {"$ref": f"#/components/schemas/{entity}"}
                                    }
                                }
                            }
                        }
                    }
                )
            ]
        }

    def generate_mcp_server(self, request: str, output_dir: str) -> bool:
        """
        Generate a complete MCP server from a natural language request

        Args:
            request: Natural language description of the API
            output_dir: Directory where the MCP server should be generated

        Returns:
            True if generation was successful, False otherwise
        """
        try:
            logger.info(f"Processing request: {request}")

            # Parse the natural language request
            parsed = self.parse_natural_language_request(request)

            # Create OpenAPI specification
            openapi_gen = OpenAPIGenerator()
            openapi_gen.api_info = parsed["info"]

            for schema in parsed["schemas"]:
                openapi_gen.add_schema(schema)

            for endpoint in parsed["endpoints"]:
                openapi_gen.add_endpoint(endpoint)

            openapi_spec = openapi_gen.generate_spec()

            # Create configuration
            config_gen = ConfigGenerator()
            config = config_gen.create_config(
                title=parsed["info"].title,
                description=parsed["info"].description
            )

            # Create temporary directory for files
            self.temp_dir = tempfile.mkdtemp(prefix="ai_scaffolding_")

            # Write OpenAPI specification
            openapi_file = os.path.join(self.temp_dir, "openapi.json")
            with open(openapi_file, 'w') as f:
                json.dump(openapi_spec, f, indent=2)

            # Write configuration file
            config_file = os.path.join(self.temp_dir, "config.yaml")
            with open(config_file, 'w') as f:
                yaml.dump(config, f, default_flow_style=False)

            logger.info(f"Generated OpenAPI spec with {len(parsed['schemas'])} schemas and {len(parsed['endpoints'])} endpoints")

            # Run openapi-mcp-codegen
            cmd = [
                "uv", "run", "python", "-m", "openapi_mcp_codegen",
                "--spec-file", openapi_file,
                "--output-dir", output_dir
            ]

            logger.info(f"Running command: {' '.join(cmd)}")

            # Change to the openapi-mcp-codegen directory to run the tool
            original_cwd = os.getcwd()
            try:
                # Find the openapi-mcp-codegen directory
                codegen_dir = None
                current_dir = original_cwd
                while current_dir != "/":
                    potential_codegen = os.path.join(current_dir, "openapi-mcp-codegen")
                    if os.path.exists(potential_codegen):
                        codegen_dir = potential_codegen
                        break
                    current_dir = os.path.dirname(current_dir)

                if codegen_dir is None:
                    raise FileNotFoundError("Could not find openapi-mcp-codegen directory")

                os.chdir(codegen_dir)
                result = subprocess.run(cmd, capture_output=True, text=True, check=True)

                # Copy the config file to the output directory
                output_config = os.path.join(output_dir, "config.yaml")
                shutil.copy2(config_file, output_config)

                logger.info(f"Successfully generated MCP server in {output_dir}")
                return True

            finally:
                os.chdir(original_cwd)

        except subprocess.CalledProcessError as e:
            logger.error(f"Error running openapi-mcp-codegen: {e}")
            logger.error(f"stderr: {e.stderr}")
            return False
        except Exception as e:
            logger.error(f"Error generating MCP server: {e}")
            return False
        finally:
            # Clean up temporary directory
            if self.temp_dir and os.path.exists(self.temp_dir):
                shutil.rmtree(self.temp_dir)

    def interactive_mode(self):
        """Run the agent in interactive mode"""
        print("🤖 AI Scaffolding Agent for MCP Server Generation")
        print("=" * 60)
        print("Describe the API you want to create in natural language.")
        print("Examples:")
        print("- 'I want a pet store API with pets, categories, and orders'")
        print("- 'Create a user management API with user profiles'")
        print("- 'Build a blog API for posts and comments'")
        print("Type 'quit' to exit.")
        print()

        while True:
            try:
                request = input("Describe the API you want to create: ").strip()

                if request.lower() in ['quit', 'exit', 'q']:
                    print("Goodbye! 👋")
                    break

                if not request:
                    continue

                # Get output directory
                default_output = f"/tmp/{request.lower().replace(' ', '_')}_mcp"
                output_dir = input(f"Output directory [{default_output}]: ").strip() or default_output

                print(f"\n🚀 Generating MCP server from: '{request}'")
                print(f"📁 Output directory: {output_dir}")
                print()

                success = self.generate_mcp_server(request, output_dir)

                if success:
                    print(f"\n✅ Success! MCP server generated at: {output_dir}")
                    print(f"📖 Check the README.md in {output_dir} for next steps")
                else:
                    print(f"\n❌ Failed to generate MCP server. Check the logs for details.")

                print("\n" + "=" * 60)

            except KeyboardInterrupt:
                print("\nGoodbye! 👋")
                break
            except Exception as e:
                print(f"\n❌ Error: {e}")
                print("Please try again or type 'quit' to exit.")


def main():
    """Main entry point"""
    import sys

    agent = AIScaffoldingAgent()

    if len(sys.argv) > 1:
        # Command line mode
        if len(sys.argv) < 3:
            print("Usage: python ai_scaffolding_agent.py \"<natural language request>\" <output_dir>")
            sys.exit(1)

        request = sys.argv[1]
        output_dir = sys.argv[2]

        success = agent.generate_mcp_server(request, output_dir)
        sys.exit(0 if success else 1)
    else:
        # Interactive mode
        agent.interactive_mode()


if __name__ == "__main__":
    main()